CREATE TABLE LOG (ID INTEGER NOT NULL, ANNÉE INTEGER, HEURE INTEGER, JOUR INTEGER, MILLISECONDES INTEGER, MINUTES INTEGER, MOIS INTEGER, SECONDES INTEGER, PRIMARY KEY (ID))
CREATE TABLE MACHINE (ID INTEGER NOT NULL, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
